#!/usr/bin/env python3
# Copyright (C) 2023 Reece H. Dunn. SPDX-License-Identifier: Apache-2.0

import conllutil
import sys
import os


def validate_conllu(filename):
    print(f"INFO: validating {filename}")


def validate_files(filename):
    if filename.endswith('.lst'):
        dirname = os.path.dirname(filename)
        for file in conllutil.parse_filelist(filename):
            conllu_filename = os.path.join(dirname, file)
            validate_conllu(conllu_filename)
    else:
        validate_conllu(filename)


def main():
    validate_files(sys.argv[1])


if __name__ == '__main__':
    main()
